[application]
ios_info_plist = "Info.plist"

[web.app]

# HTML title tag content
title = "test-app"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle.macos]
files = { "AppIcon60x60@2x.png" = "assets/AppIcon60x60@2x.png", "AppIcon76x76@2x~ipad.png" = "assets/AppIcon76x76@2x~ipad.png" }
